### ISSUE TITLE
Testing the saved models

### ISSUE THREAD

**Issue by dhawaldarji7** [guardiaum/BERT-SIDE#17]
How can I test the saved models on my own data?
Thanks!

**Comment by guardiaum** [comment]
Hi @dhawaldarji7, first you have to get the BERT sentence representation (the embedding of the [CLS] marker) for each example in your test set. For this you can use the [bert-as-service](https://github.com/hanxiao/bert-as-service), the [Transformers API](https://github.com/huggingface/transformers), or any other API for BERT.

Then you have to format your test data to follow the same structure of the GIDS and RIEDEL datasets present [HERE](https://drive.google.com/file/d/1LIeKCjnrBWIS0rOw2sfcUn349qmW_8Q-/view?usp=sharing). If you already have the external KG and alias information you can just format it and include it into your preprocessed data, otherwise you may use the GIDS or RIEDEL external information as you wish.

After this, you can follow the code present in the notebooks [_GIDS_bert_side.ipynb_](https://github.com/guardiaum/BERT-SIDE/blob/master/GIDS_bert_side.ipynb) or [_RIEDEL_bert_side.ipynb_](https://github.com/guardiaum/BERT-SIDE/blob/master/RIEDEL_bert_side.ipynb). On the last notebooks' cells you find how to load the pretrained model, how to perform the predictions over the test data, save the predictions to file, plot the results and get the P@N results.

For more implementation details you can check our paper https://arxiv.org/abs/2004.14443
